version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: schoman_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: schoman
    volumes:
      - mongodb_data:/data/db
    networks:
      - schoman_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: schoman_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/schoman
      - JWT_SECRET=${JWT_SECRET:-change_this_secret_in_production}
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongodb
    networks:
      - schoman_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: schoman_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    networks:
      - schoman_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  schoman_network:
    driver: bridge

volumes:
  mongodb_data:
