# Prometheus Configuration for Schoman
# This file configures Prometheus to scrape metrics from Schoman services

global:
  scrape_interval: 15s  # How frequently to scrape targets
  evaluation_interval: 15s  # How frequently to evaluate rules
  scrape_timeout: 10s  # Timeout for scraping targets
  
  # Attach these labels to any time series or alerts
  external_labels:
    monitor: 'schoman-monitor'
    environment: 'production'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'  # Uncomment to enable alerting

# Load rules once and periodically evaluate them
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Schoman Backend API
  - job_name: 'schoman-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:3000']
        labels:
          service: 'backend'
          tier: 'api'
    # Only scrape if service is healthy
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: backend:3000

  # MongoDB metrics (requires mongodb_exporter)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
        labels:
          service: 'mongodb'
          tier: 'database'

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          tier: 'cache'

  # Node Exporter for system metrics (optional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'
          tier: 'infrastructure'

  # Nginx metrics (requires nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx'
          tier: 'proxy'

  # Additional Schoman services can be added here
  # Example: Frontend server (if serving metrics)
  # - job_name: 'schoman-frontend'
  #   static_configs:
  #     - targets: ['frontend:5173']
  #       labels:
  #         service: 'frontend'
  #         tier: 'web'
